import { Property, Product } from "@/types/property";

export const properties: Property[] = [
  {
    id: 1,
    images: [
      { img: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c" },
      { img: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c" },
      { img: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c" },
    ],
    title: "Modern Family Home",
    description: "A spacious, energy-efficient home with a contemporary design.",
    location: "Madison, WI",
    price: "$450,000",
    bedrooms: 4,
    bathrooms: 3,
    area: "2,500 sqft",
    status: "FOR_SALE",
    type: "HOUSE",
    featured: true,
    viewCount: 120,
    listedById: 1,
    listedBy: {
      id: 1,
      email: "admin@winconstructures.com",
      firstName: "Admin",
      lastName: "User",
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    images: [
      { img: "https://images.unsplash.com/photo-1560185893-a55cbc8c57e8" },
      { img: "https://images.unsplash.com/photo-1560185949-67d2f8f423e8" },
    ],
    title: "Downtown Luxury Condo",
    description: "A sleek condo with panoramic city views, built by Wiscon Structures.",
    location: "Milwaukee, WI",
    price: "$2,000",
    bedrooms: 2,
    bathrooms: 2,
    area: "1,200 sqft",
    status: "FOR_RENT",
    type: "CONDO",
    featured: false,
    viewCount: 85,
    listedById: 1,
    listedBy: {
      id: 1,
      email: "admin@winconstructures.com",
      firstName: "Admin",
      lastName: "User",
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    images: [
      { img: "https://images.unsplash.com/photo-1572120360138-8b5e47cbae80" },
      { img: "https://images.unsplash.com/photo-1572120360138-8b5e47cbae81" },
      { img: "https://images.unsplash.com/photo-1572120360138-8b5e47cbae82" },
      { img: "https://images.unsplash.com/photo-1572120360138-8b5e47cbae83" },
    ],
    title: "Urban Studio Apartment",
    description: "A compact, modern apartment perfect for city living.",
    location: "Green Bay, WI",
    price: "$250,000",
    bedrooms: 1,
    bathrooms: 1,
    area: "800 sqft",
    status: "FOR_SALE",
    type: "APARTMENT",
    featured: false,
    viewCount: 92,
    listedById: 1,
    listedBy: {
      id: 1,
      email: "admin@winconstructures.com",
      firstName: "Admin",
      lastName: "User",
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    images: [
      { img: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c" },
      { img: "https://images.unsplash.com/photo-1600566753086-1035a4e81367" },
      { img: "https://images.unsplash.com/photo-1600585154526-990dced4db0d" },
    ],
    title: "Suburban Retreat",
    description: "A cozy house with a large backyard, ideal for families.",
    location: "Appleton, WI",
    price: "$1,800",
    bedrooms: 3,
    bathrooms: 2,
    area: "1,800 sqft",
    status: "FOR_RENT",
    type: "HOUSE",
    featured: false,
    viewCount: 67,
    listedById: 1,
    listedBy: {
      id: 1,
      email: "admin@winconstructures.com",
      firstName: "Admin",
      lastName: "User",
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Legacy data format for admin dashboard (can be phased out)
export const data: Product[] = [
  { id: 1, image: "/logo.png", name: 'Gadgetex', price: '$20', orders: 40, stock: 300, amount: 6000 },
  { id: 2, image: "/logo.png", name: 'Gadgetable', price: '$30', orders: 35, stock: 250, amount: 6200 },
  { id: 3, image: "/logo.png", name: 'Module Gadget', price: '$24', orders: 60, stock: 257, amount: 5300 },
  { id: 4, image: "/logo.png", name: 'Rubicon Gadget', price: '$25', orders: 46, stock: 278, amount: 5600 },
  { id: 5, image: "/logo.png", name: 'Gadgetish', price: '$26', orders: 34, stock: 267, amount: 4500 },
  { id: 6, image: "/logo.png", name: 'Zone Gadget', price: '$27', orders: 37, stock: 287, amount: 5700 },
  { id: 7, image: "/logo.png", name: 'Gadgetnest', price: '$20', orders: 76, stock: 285, amount: 4300 },
];